# Generated by Django 5.0.6 on 2024-06-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0004_waterinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapWaterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province', models.CharField(max_length=30)),
                ('Class', models.IntegerField()),
                ('temp', models.FloatField()),
                ('pH', models.FloatField()),
                ('Ox', models.FloatField()),
                ('Dao', models.FloatField()),
                ('Zhuodu', models.FloatField()),
                ('Yandu', models.FloatField()),
                ('Andan', models.FloatField()),
                ('Zonglin', models.FloatField()),
                ('Zongdan', models.FloatField()),
            ],
        ),
    ]
