# Generated by Django 5.0.6 on 2024-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo', '0005_mapwaterinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishBaike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('alias', models.CharField(max_length=128)),
                ('distribution', models.CharField(max_length=256)),
                ('food', models.CharField(max_length=256)),
                ('appearance', models.TextField(max_length=1024)),
                ('brief_intro', models.TextField(max_length=2048)),
            ],
        ),
    ]
